name: ikinci_cli
description: IKINCI KANAL Command Line Interface
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  ikinci_core:
    path: ../../packages/ikinci_core
  args: ^2.4.2
  interact_cli: ^2.1.1
  ansi_styles: ^0.3.2
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  ikinci: ikinci
